### ISSUE TITLE
Error/regression in 1.18 vs 1.16 dynamic function selection

### ISSUE THREAD

**Issue by CheshireSwift** [xMGZx/UnifyTags#15]
In commit 7d239870755074cab2da952e18c50d5d7275634d the `fname` variable (selecting `getObjectIds` vs `getAllItemIds`) was removed, but it's still used [on line 244](https://github.com/xMGZx/UnifyTags/blob/main/server_scripts/unify.js#L244), leading to runtime errors.

**Comment by mathgeniuszach** [comment]
Fixed in https://github.com/xMGZx/UnifyTags/commit/7cff83a239c0d7079a570704c422bcad3f835d21
