### ISSUE TITLE
Error in script : Undeclared variable

### ISSUE THREAD

**Issue by Gamephantom** [xMGZx/UnifyTags#18]
With the newest update of KubeJS, the script now throws errors:

`[12:03:16] [ERR  ] Error loading KubeJS script: Assignment to undeclared variable invnames (server_scripts:unify.js#385)`

Minecraft: 1.18.2
KubeJS Version: 1802.5.5-build.546

**Comment by mathgeniuszach** [comment]
Fixed by https://github.com/xMGZx/UnifyTags/commit/bee897afa35239ab4a075fab98679586674caa56
