### ISSUE TITLE
entity.spawned error in server console

### ISSUE THREAD

**Issue by Guardian9978** [xMGZx/UnifyTags#2]
Minecraft Version: 1.16.5
Server Type: Forge
Forge Version: 36.0.46
Mod Version: 1.1
KubeJS Version: 1605.3.6-build.172

Every time an item is spawned in the world such as dropped by a player or dropped from a block that was mined this error is displayed in the server console:
`[02:59:56] [Server thread/ERROR] [KubeJS Server/]: Error occurred while handling event 'entity.spawned': Wrapped java.lang.NullPointerException (server_scripts:unify.js#136)`

Despite the error it still converts the Ores and Ingots but would like to not have an error spam my server console.

**Comment by mathgeniuszach** [comment]
Seems to be an issue with it trying to unify tags that don't exist. I added an if statement to check it now, but if that doesn't help, try removing tags from the tagGen list that don't exist.
