### ISSUE TITLE
[1.19.2] Script errors in the new KubeJS alpha

### ISSUE THREAD

**Issue by Vapaman** [xMGZx/UnifyTags#20]
### **Error Message**
[20:16:03] [ERR  ] Error loading KubeJS script: server_scripts:unify.js: Line 176: 'onEvent()' is no longer supported! Read more on wiki: https://kubejs.com/kjs6

**Instructions on fixing**
https://mods.latvian.dev/books/kubejs/page/migrating-to-kubejs-6

### **Versions:**
KubeJS Forge 1902.6.0-build.101
Rhino Forge 1902.2.1-build.247

**Comment by mathgeniuszach** [comment]
dumb... I still have to _support_ older versions that still use `onEvent()`. So in reality I can't just change onEvent, I have to put a version check in place that surrounds every single function

**Comment by mathgeniuszach** [comment]
Fixed by https://github.com/xMGZx/UnifyTags/commit/6abd7217b5c5758e0e52be85008b388df10c0f77

**Comment by Vapaman** [comment]
Thank you so much for fixing this! <3
