### ISSUE TITLE
These scripts crashed my computer

### ISSUE THREAD

**Issue by ghost** [xMGZx/UnifyTags#22]
After adding these scripts to the my mod pack folder and opening the game, my computer crashed and when I tried again, the same happened.

**Comment by mathgeniuszach** [comment]
I cannot help you or verify your problem without a crash report and information on your installation process. These scripts have worked fine for me, so how can I be sure you didn't just make a mistake?

**Comment by ghost** [comment]
i changed few settings in scripts and then pc crashed but after removing scripts there was no problem

**Comment by mathgeniuszach** [comment]
You didn't provide either of the things I asked for. How do I know you didn't just install the scripts wrong? More importantly, if it is an issue with the scripts, how am I supposed to fix it with no information?

**Comment by ghost** [comment]
Sorry, the problem is not in your scripts, I'm so sorry
