### ISSUE TITLE
Error in server script

### ISSUE THREAD

**Issue by HakeemAzma** [xMGZx/UnifyTags#23]
[ERROR] ! #355: Error occurred while handling event 'ServerEvents.recipes': TypeError: Cannot call method "forEach" of undefined (server_scripts:unify.js#355)

**Comment by mathgeniuszach** [comment]
Only thing I can recommend is turning off recipe de-dupe, downgrading KubeJS, or looking into a newer replacement mod like [Almost Unified](https://modrinth.com/mod/almost-unified) (which has versions from 1.18.2+)

KubeJS keeps making breaking changes to nearly all their internals all the time, so it's nearly impossible for me to fix everything.
