### ISSUE TITLE
How should I convert items

### ISSUE THREAD

**Issue by HaiXi2912** [xMGZx/UnifyTags#25]
For example,convert cavesandcliffs:deepslate to quark:deepslate, their dictionaries all include forge: stone and cavesandcliffs:deepslate. I've been trying for a long time but haven't figured it out. Can you help me answer this question

**Comment by mathgeniuszach** [comment]
You'll probably want to use the `tagSplits` or `customtags` fields to make your own tags to be unified. `tagSplits` was designed for this exact use case!
