### ISSUE TITLE
[Suggestion] Support for Emendatus Enigmatica

### ISSUE THREAD

**Issue by ghost** [xMGZx/UnifyTags#6]
Can you implement a support for Emendatus Enigmatica? This mod nicely unify the stuffs in the game except for recipes.

**Comment by Switch-Back18** [comment]
add EmendatusEnigmatica in mod priority

**Comment by ghost** [comment]
> add EmendatusEnigmatica in mod priority

So its supports it, just isn’t in the default priority list?

**Comment by mathgeniuszach** [comment]
Yes, but now it is.
