### ISSUE TITLE
JEI Items not hide when we login in server !

### ISSUE THREAD

**Issue by Switch-Back18** [xMGZx/UnifyTags#7]
If add this code un kubejs !

In solo the items unified is hide but, when i'm login in server that he has the server script, the unified items is not hide

**Comment by MrAkells** [comment]
I also noticed such a problem. Someone knows how to fix it?

**Comment by mathgeniuszach** [comment]
It's possible that on a live server, the client doesn't have access to the server tags, and so they cannot be hidden from JEI. I'm not exactly sure though.

**Comment by mathgeniuszach** [comment]
Use the most recent version of the script (download it from github) and enable the cache. Make sure everyone has the same copy of the cache, client and server. See the readme for more information about the cache.
