### ISSUE TITLE
Confusion with raw ores

### ISSUE THREAD

**Issue by maxbeer99** [xMGZx/UnifyTags#8]
I was unsure if this is the correct place but a simple Kubejs script seems to be the easiest solution. There seems to be a bit of confusion regarding the usage of tags for raw ores in 1.18, causing many recipes and compatibility to break. For example, AllTheOres uses tags of the form `forge:raw_ores/raw_xxx` while immersive engineering in my case uses `forge:raw_ores/xxx` which seems to be more in line with other tags. Maybe adding a few lines to unify this to the script could be usefull. While I have some js experience getting this to work in minecraft could take some considerable amount of time for me so I just wanted to suggest it here.

**Comment by mathgeniuszach** [comment]
It seems like this is fixed in 1.18.2, potentially it was fixed before that. I have added the proper raw_materials tags into the defaults.
