### ISSUE TITLE
how do i use this

### ISSUE THREAD

**Issue by inikishev** [xMGZx/UnifyTags#9]
I don't get it

**Comment by mathgeniuszach** [comment]
There is an installation guide in the description. You ought to be familiar with where your .minecraft folder is in the pack you're trying to add UnifyTags too. Configuration options are available in the `server_scripts/unify.js` file.

**Comment by inikishev** [comment]
> There is an installation guide in the description. You ought to be familiar with where your .minecraft folder is in the pack you're trying to add UnifyTags too. Configuration options are available in the `server_scripts/unify.js` file.

i don't get configuragtion options. Lets say there are two steel ores, how do i make them into one steel ore

**Comment by mathgeniuszach** [comment]
You add them to a tag and add that to the tags to be unified, or if they're already in a tag, add that tag to the list of tags to be unified. There's not really much more I can say, if you don't understand what an item tag is, I recommend you search it up on the Minecraft wiki.

**Comment by inikishev** [comment]
> 

how do i add them to a tag

**Comment by jimmon89** [comment]
on my personal pack i added tags to vinteum or from mana and artifice, dark ore from evilcraft, and the various dimensional shard ore from RFTools like so in a file with a .js extension in `*your minecraft folder*\kubejs\server_scripts\`
in my case i named the file `jimmon.js` but the name of the file doesn't matter, just the .js extension
```
onEvent('tags.items', event => {
	//Mana and Artifice
	//fix ores
	event.add('forge:ores/vinteum', 'mana-and-artifice:vinteum_ore');
	//EvilCraft
	//fix ores
	event.add('forge:ores/dark_gem', 'evilcraft:dark_ore');
	//RFTools
	//fix ores
	event.add('forge:ores/dimensional_shard', 'rftoolsbase:dimensionalshard_overworld');
	event.add('forge:ores/dimensional_shard', 'rftoolsbase:dimensionalshard_nether');
	event.add('forge:ores/dimensional_shard', 'rftoolsbase:dimensionalshard_end');
});
```
